# -*- coding: utf-8 -*-
"""lesson_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umBQAdssghZQD8C6JXa0ZHKK7rQunx8T
"""

2+5

print('Hello World!')

print("Hello World.")

adjective = input("Please enter an adjective: ")
noun = input("Please enter a noun: ")
verb = input("Please enter a verb ending in -ed: ")
print("Your MadLib:")
print("The", adjective, noun, verb, "over the lazy brown dog.")

